[META]
DOL_Office = "__TEMPLATE__"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "s4", 90.188, 711366.012],
  [2, "B", "525", 86.031, 711452.043],
  [3, "C", "526", 10.306, 711441.737],
  [4, "D", "527", 31.422, 711473.159],
  [5, "E", "528", 3.868, 711469.291],
  [6, "F", "s29", 57.311, 711526.602],
  [7, "G", "s31", 98.233, 711624.835],
  [8, "H", "532", 62.146, 711562.689],
  [9, "I", "533", 11.353, 711574.042],
  [10, "J", "581.", 117.842, 711456.200],
]