[META]
DOL_Office = "__TEMPLATE__"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "542", 70.858, 711420.856],
  [2, "B", "s22", 92.142, 711328.714],
  [3, "C", "523", 159.395, 711488.109],
  [4, "D", "530", 93.367, 711581.476],
  [5, "E", "s29", 54.874, 711526.602],
  [6, "F", "528", 57.311, 711469.291],
  [7, "G", "s27", 3.868, 711473.159],
  [8, "H", "526", 31.422, 711441.737],
  [9, "I", "s25", 10.306, 711452.043],
  [10, "J", "s4", 86.031, 711366.012],
  [11, "K", "543", 16.014, 711349.998],
]