[META]
DOL_Office = "__TEMPLATE__"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "531", 19.631, 711624.835],
  [2, "B", "529", 98.233, 711526.602],
  [3, "C", "530", 54.874, 711581.476],
  [4, "D", "513", 119.551, 711701.027],
  [5, "E", "$80.", 56.561, 711644.466],
]