[META]
DOL_Office = "__TEMPLATE__"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = true
marker = [
  [1, "A", "s80.", 711644.466, 810031.568],
  [2, "B", "s31", 711624.835, 810051.076],
  [3, "C", "s29", 711526.602, 810148.263],
  [4, "D", "s30", 711581.476, 810204.956],
  [5, "E", "s13", 711701.027, 810081.178],
]