[META]
DOL_Office = "__TEMPLATE__"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = true
marker = [
  [1, "A", "s24", 711494.218, 810313.001],
  [2, "B", "s18", 711510.841, 810323.391],
  [3, "C", "s17", 711619.233, 810248.648],
  [4, "D", "s30", 711581.476, 810204.956],
  [5, "E", "s23", 711488.109, 810300.804],
]