[META]
DOL_Office = "__TEMPLATE__"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "s18", 16.623, 711510.841],
  [2, "B", "s17", 108.392, 711619.233],
  [3, "C", "s30", 37.757, 711581.476],
  [4, "D", "s23", 93.367, 711488.109],
  [5, "E", "524", 6.109, 711494.218],
]