[META]
DOL_Office = "__TEMPLATE__"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = true
marker = [
  [1, "A", "s41", 711042.723, 810293.807],
  [2, "B", "s20", 711275.096, 810520.089],
  [3, "C", "s21", 711325.209, 810466.417],
  [4, "D", "s19", 711354.507, 810440.839],
  [5, "E", "s24", 711494.218, 810313.001],
  [6, "F", "s23", 711488.109, 810300.804],
  [7, "G", "s22", 711328.714, 810147.726],
  [8, "H", "s42", 711420.856, 810053.505],
  [9, "I", "s43", 711349.998, 809983.554],
]