[META]
DOL_Office = "__TEMPLATE__"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "s20", 232.373, 711275.096],
  [2, "B", "s21", 50.113, 711325.209],
  [3, "C", "s19", 29.298, 711354.507],
  [4, "D", "s24", 0.140, 711494.218],
  [5, "E", "$23", 6.109, 711488.109],
  [6, "F", "s22", 159.395, 711328.714],
  [7, "G", "s42", 92.142, 711420.856],
  [8, "H", "s43", 70.858, 711349.998],
  [9, "I", "541", 307.275, 711042.723],
]